name = "workers-do"
routes = [
  { pattern = "*/*", zone_name = "workers.do" },
  { pattern = "*.入.io/*", zone_name = "入.io" },
]
main = "worker.js"
compatibility_date = "2022-08-25"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

[[kv_namespaces]]
  binding = "PLATFORM_DOMAINS"
  id = "8076b94771a14195abe77f9f1c8988a8"
  preview_id = "8076b94771a14195abe77f9f1c8988a8"

[[dispatch_namespaces]]
binding = "dispatcher"
namespace = "example-namespace"
